### PR TITLE
reed.configure()

### PR DESCRIPTION
**Pull request by algesten**
That should be it.

### CODE REVIEW

**Comment by ProjectMoon** [comment]
A few issues with this before it can be merged:
- The call to `client.auth` should catch the error from the callback and then do `reed.emit('error', err)` if the error exists.
- Catching the error event with `client.on('error')` should not log and end the process. It needs to emit a reed error event only.

Edit: I fail at git merging. Ignore the part about the URL stuff.

**Comment by algesten** [comment]
Uhm... where do you find the redis URL module? I thought I removed all such things.

Ok, I'll fix the client.auth error.

M

**Comment by ProjectMoon** [comment]
The URL module was because I need to learn how to use meld to merge things in Git. I edited the comment.

**Comment by algesten** [comment]
got it

**Comment by algesten** [comment]
I opted for throw new Error(). If I just re-emit the event, I get a very nondescript stack trace without any indication as to what went wrong - but it really is shafted. Is that okay?

**Comment by ProjectMoon** [comment]
I am in the process of merging this. Can you describe how to reproduce the error that leads to your throw statement? Is it if authentication fails?

**Comment by algesten** [comment]
Run redis as usual and do reed.configure(password: 'anything') followed by open;

M

**Comment by ProjectMoon** [comment]
So, redis without a password? When I set Redis to have no password, but give reed a password, it still executes fine. `redis-cli` returns OK for any password given to the auth command.

When I set redis to have a password and then give it the wrong one, it throws the error in the callback you added.

**Comment by algesten** [comment]
Yeah. Redis without password. Reed with. I get this if I don't have the handler. That's what I mean by "nondescript":

```
Error: Uncaught, unspecified 'error' event.
    at RedisClient.emit (events.js:50:15)
    at Command.callback (/Users/martin/dev/karlkajal/node_modules/redis/index.js:159:29)
    at RedisClient.return_error (/Users/martin/dev/karlkajal/node_modules/redis/index.js:446:25)
```

But I'm new to node development. Perhaps this is expected?

**Comment by ProjectMoon** [comment]
What version of Redis are you using?

**Comment by algesten** [comment]
2.4.4

**Comment by ProjectMoon** [comment]
Ok, I was using 2.2. Redis 2.2 just silently accepts all passwords if there is no password set. Redis 2.4.4 throws an error back saying password is not set.

So anyway, if I set the code to do `reed.emit('error', errMsg);` and then do this:

```
reed.on('error', function(err) {
    console.log(err);
});
```

I get `Auth error: Error: ERR Client sent AUTH, but no password is set` as output.

**Comment by algesten** [comment]
Yes, that's what I'm seeing too.

I'm not that worried about it. I just thought the default `Error: Uncaught, unspecified 'error' event.` was a bit unhelpful. But we could just drop the error handler...

**Comment by ProjectMoon** [comment]
Well that's the thing. I can't get reed to do emit your unspecified error event. When I make it emit instead of throw, I get the auth error message into the callback.

**Comment by algesten** [comment]
Great! Then we can just put it down to my environment. I'm using it through coffee-script.

**Comment by ProjectMoon** [comment]
What version of node and node-redis are you using? It could be an issue in tone of those.

**Comment by algesten** [comment]
node 0.6.5
node-redis 0.7.1
coffee-script 1.1.3

**Comment by ProjectMoon** [comment]
Well apparently my test environment was out of date. I upgraded from node-redis 0.6.0. Nevertheless, I still got the right error message. For now, I'm going to change it to emit an error event.

**Comment by algesten** [comment]
Sounds like a plan.

**Comment by ProjectMoon** [comment]
0.9.7 has been pushed out to NPM with these changes. I changed the code style a bit and also went through and made sure the documentation was up to snuff.

**Pull request closed without merging**
