### PR TITLE
try-catch attempt

### PR DESCRIPTION
**Pull request by algesten**
I tried to fix the issue with try-catch as per your suggestion.

### CODE REVIEW

**Comment by algesten** [comment]
Okay, didn't know that additional commits are being inserted into the pull request. 54f68b1 is obviously the only one I propose to pull at this stage.

**Comment by ProjectMoon** [comment]
Ok, I cherry-picked the first commit (the one that adds try-catch) and pushed version 0.9.6. The other stuff is a separate issue.

**Comment by algesten** [comment]
Thanks! ... i need to figure out how my subsequent commits should now show in the pull req.

**Comment by ProjectMoon** [comment]
I think it's based on branch. Since this was from your master branch on the fork, everything gets dumped into it.

**Pull request closed without merging**
